import { INavLinks } from '../components/types'

export const navLinks: INavLinks[] = [
  {
    title: 'About',
    path: '#about',
  },
  {
    title: 'Skills',
    path: '#skills',
  },
  {
    title: 'Projects',
    path: '#projects',
  },
  {
    title: 'Contacts',
    path: '#contact',
  },
]

export const projectsData = [
  {
    id: 1,
    title: 'Нити света',
    description: 'Благотворительный интернет магазин',
    image: '/projects/12.png',
    tag: ['All', 'Commercial', 'Frontend'],
    previewUrl: 'https://nitisveta.ru/',
  },
  {
    id: 2,
    title: 'Bua Thai',
    description: 'Спа-салон тайского массажа',
    image: '/projects/13.png',
    tag: ['All', 'Commercial', 'Frontend'],
    previewUrl: 'https://buathai.ru/spb/spa',
  },
  {
    id: 3,
    title: 'Berrybook',
    description: 'Верный спутник в путешествии!',
    image: '/projects/14.png',
    tag: ['All', 'Commercial', 'Frontend'],
    previewUrl: 'https://berrybook.com/',
  },
  {
    id: 4,
    title: 'Project: Music Service',
    description: 'Служба домашней библиотеки!',
    // description:
    //   'Created a Home Library Service! Users can create, read, update, delete data about Artists, Tracks and Albums, add them to Favorites in their own Home Library!',
    image: '/projects/1.png',
    tag: ['All', 'Backend'],
    gitUrl: 'https://github.com/conservativ007/nodejs2022Q4-service',
    previewUrl: '/',
  },
  // {
  //   id: 5,
  //   title: 'Онлайн чат',
  //   description: 'Общайтесь с друзьями, знакомтесь!',
  //   // title: 'Project: Chat Service',
  //   // description:
  //   //   'The chat Service, you can create a user and communicate with another people. Send messages, send emoticons, like messages, edit and delete messages, there is a general chat and a private chat',
  //   image: '/projects/2.png',
  //   tag: ['All', 'Front+Back'],
  //   gitUrl: 'https://github.com/conservativ007/chat-server',
  //   previewUrl: 'http://chat-app.by/',
  // },
  {
    id: 6,
    title: 'Anime',
    description: 'NextJS - Server Actions',
    // title: 'Learning english words',
    // description: 'Learn English words with flashcards',
    image: '/projects/11.png',
    tag: ['All', 'Frontend'],
    gitUrl: 'https://github.com/conservativ007/next-anime_vault',
    previewUrl: 'https://next-anime-vault-woad.vercel.app/',
  },
  // {
  //   id: 4,
  //   title: 'Learning english words',
  //   description: 'Приложение для изучения Английских слов',
  //   image: '/projects/3.png',
  //   tag: ['All', 'Frontend'],
  //   gitUrl: 'https://github.com/conservativ007/learn-english',
  //   previewUrl: 'https://learn-english-by-conservative.netlify.app/',
  // },
  {
    id: 7,
    title: 'Shelter',
    description: 'Сайт помощи бездомным животным',
    // description: 'Shelter not only people need a house',
    image: '/projects/4.png',
    tag: ['All', 'Frontend'],
    gitUrl: 'https://github.com/conservativ007/shelter',
    previewUrl: 'https://conservativ007.github.io/shelter/',
  },
  // {
  //   id: 6,
  //   title: 'Пазл',
  //   description: 'Попробуй свои силы в пазле',
  //   // title: 'Puzzle',
  //   // description: 'Lich king theme puzzle',
  //   image: '/projects/5.2.png',
  //   tag: ['All', 'Frontend'],
  //   gitUrl: 'https://github.com/rolling-scopes-school/conservativ007-JS2020Q3',
  //   previewUrl:
  //     'https://rolling-scopes-school.github.io/conservativ007-JS2020Q3/game-puzzle/',
  // },
  {
    id: 8,
    title: 'Momentum',
    description: 'Приложение погоды',
    // description: 'Clone of the application of the same name',
    image: '/projects/6.2.png',
    tag: ['All', 'Frontend'],
    gitUrl: 'https://github.com/conservativ007/momentum-r',
    previewUrl: 'https://momentum-r.vercel.app/',
  },
  {
    id: 9,
    title: 'Web dev',
    description: 'Вёрстка',
    // description: 'Layout',
    image: '/projects/7.png',
    tag: ['All', 'Frontend'],
    gitUrl: 'https://github.com/conservativ007/webdev',
    previewUrl: 'https://conservativ007.github.io/webdev/',
  },
  {
    id: 10,
    title: 'Английский для детей',
    description: 'Изучение некоторых английских слов для самых маленьких',
    // title: 'English for kids',
    // description: 'Learning some English words for little ones',
    image: '/projects/8.png',
    tag: ['All', 'Frontend'],
    gitUrl: 'https://github.com/conservativ007/english-for-kids',
    previewUrl: 'https://conservativ007.github.io/english-for-kids/',
  },
  {
    id: 11,
    title: 'Крестики нолики',
    description: 'Игра крестики нолики',
    // title: 'Tic Tac Toe',
    // description: 'Tic Tac Toe game',
    image: '/projects/9.png',
    tag: ['All', 'Frontend'],
    gitUrl: 'https://github.com/conservativ007/react-game',
    previewUrl: 'https://tic-tac-toe-conservative.netlify.app/',
  },
  {
    id: 12,
    title: 'Бегущий по лезвию',
    description: 'Игра бегущий по лезвию',
    // title: 'Blade runner',
    // description: 'Blade runner game',
    image: '/projects/10.png',
    tag: ['All', 'Frontend'],
    gitUrl: 'https://github.com/conservativ007/rsclone',
    previewUrl: 'https://blade-runner-2021.netlify.app/',
  },
]
